/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthErrorIndexRouteImport } from './routes/auth/error/index'
import { Route as ProtectedPanelIndexRouteImport } from './routes/_protected/panel/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiContentSearchRouteImport } from './routes/api/content/search'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedPanelguestRosterIndexRouteImport } from './routes/_protected/panel/(guest)/roster/index'
import { Route as ProtectedPaneladminWeaponsIndexRouteImport } from './routes/_protected/panel/(admin)/weapons/index'
import { Route as ProtectedPaneladminResonatorsIndexRouteImport } from './routes/_protected/panel/(admin)/resonators/index'
import { Route as ProtectedPaneladminMaterialsIndexRouteImport } from './routes/_protected/panel/(admin)/materials/index'
import { Route as ProtectedPaneladminEchoesIndexRouteImport } from './routes/_protected/panel/(admin)/echoes/index'
import { Route as ProtectedPaneladminWeaponsCreateRouteImport } from './routes/_protected/panel/(admin)/weapons/create'
import { Route as ProtectedPaneladminWeaponsIdRouteImport } from './routes/_protected/panel/(admin)/weapons/$id'
import { Route as ProtectedPaneladminResonatorsCreateRouteImport } from './routes/_protected/panel/(admin)/resonators/create'
import { Route as ProtectedPaneladminResonatorsIdRouteImport } from './routes/_protected/panel/(admin)/resonators/$id'
import { Route as ProtectedPaneladminMaterialsCreateRouteImport } from './routes/_protected/panel/(admin)/materials/create'
import { Route as ProtectedPaneladminMaterialsIdRouteImport } from './routes/_protected/panel/(admin)/materials/$id'
import { Route as ProtectedPaneladminEchoesCreateRouteImport } from './routes/_protected/panel/(admin)/echoes/create'
import { Route as ProtectedPaneladminEchoesIdRouteImport } from './routes/_protected/panel/(admin)/echoes/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthErrorIndexRoute = AuthErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedPanelIndexRoute = ProtectedPanelIndexRouteImport.update({
  id: '/panel/',
  path: '/panel/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentSearchRoute = ApiContentSearchRouteImport.update({
  id: '/api/content/search',
  path: '/api/content/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPanelguestRosterIndexRoute =
  ProtectedPanelguestRosterIndexRouteImport.update({
    id: '/panel/(guest)/roster/',
    path: '/panel/roster/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminWeaponsIndexRoute =
  ProtectedPaneladminWeaponsIndexRouteImport.update({
    id: '/panel/(admin)/weapons/',
    path: '/panel/weapons/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminResonatorsIndexRoute =
  ProtectedPaneladminResonatorsIndexRouteImport.update({
    id: '/panel/(admin)/resonators/',
    path: '/panel/resonators/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminMaterialsIndexRoute =
  ProtectedPaneladminMaterialsIndexRouteImport.update({
    id: '/panel/(admin)/materials/',
    path: '/panel/materials/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminEchoesIndexRoute =
  ProtectedPaneladminEchoesIndexRouteImport.update({
    id: '/panel/(admin)/echoes/',
    path: '/panel/echoes/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminWeaponsCreateRoute =
  ProtectedPaneladminWeaponsCreateRouteImport.update({
    id: '/panel/(admin)/weapons/create',
    path: '/panel/weapons/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminWeaponsIdRoute =
  ProtectedPaneladminWeaponsIdRouteImport.update({
    id: '/panel/(admin)/weapons/$id',
    path: '/panel/weapons/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminResonatorsCreateRoute =
  ProtectedPaneladminResonatorsCreateRouteImport.update({
    id: '/panel/(admin)/resonators/create',
    path: '/panel/resonators/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminResonatorsIdRoute =
  ProtectedPaneladminResonatorsIdRouteImport.update({
    id: '/panel/(admin)/resonators/$id',
    path: '/panel/resonators/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminMaterialsCreateRoute =
  ProtectedPaneladminMaterialsCreateRouteImport.update({
    id: '/panel/(admin)/materials/create',
    path: '/panel/materials/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminMaterialsIdRoute =
  ProtectedPaneladminMaterialsIdRouteImport.update({
    id: '/panel/(admin)/materials/$id',
    path: '/panel/materials/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminEchoesCreateRoute =
  ProtectedPaneladminEchoesCreateRouteImport.update({
    id: '/panel/(admin)/echoes/create',
    path: '/panel/echoes/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaneladminEchoesIdRoute =
  ProtectedPaneladminEchoesIdRouteImport.update({
    id: '/panel/(admin)/echoes/$id',
    path: '/panel/echoes/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/content/search': typeof ApiContentSearchRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/panel/': typeof ProtectedPanelIndexRoute
  '/auth/error/': typeof AuthErrorIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/panel/echoes/$id': typeof ProtectedPaneladminEchoesIdRoute
  '/panel/echoes/create': typeof ProtectedPaneladminEchoesCreateRoute
  '/panel/materials/$id': typeof ProtectedPaneladminMaterialsIdRoute
  '/panel/materials/create': typeof ProtectedPaneladminMaterialsCreateRoute
  '/panel/resonators/$id': typeof ProtectedPaneladminResonatorsIdRoute
  '/panel/resonators/create': typeof ProtectedPaneladminResonatorsCreateRoute
  '/panel/weapons/$id': typeof ProtectedPaneladminWeaponsIdRoute
  '/panel/weapons/create': typeof ProtectedPaneladminWeaponsCreateRoute
  '/panel/echoes/': typeof ProtectedPaneladminEchoesIndexRoute
  '/panel/materials/': typeof ProtectedPaneladminMaterialsIndexRoute
  '/panel/resonators/': typeof ProtectedPaneladminResonatorsIndexRoute
  '/panel/weapons/': typeof ProtectedPaneladminWeaponsIndexRoute
  '/panel/roster/': typeof ProtectedPanelguestRosterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/content/search': typeof ApiContentSearchRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/panel': typeof ProtectedPanelIndexRoute
  '/auth/error': typeof AuthErrorIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/panel/echoes/$id': typeof ProtectedPaneladminEchoesIdRoute
  '/panel/echoes/create': typeof ProtectedPaneladminEchoesCreateRoute
  '/panel/materials/$id': typeof ProtectedPaneladminMaterialsIdRoute
  '/panel/materials/create': typeof ProtectedPaneladminMaterialsCreateRoute
  '/panel/resonators/$id': typeof ProtectedPaneladminResonatorsIdRoute
  '/panel/resonators/create': typeof ProtectedPaneladminResonatorsCreateRoute
  '/panel/weapons/$id': typeof ProtectedPaneladminWeaponsIdRoute
  '/panel/weapons/create': typeof ProtectedPaneladminWeaponsCreateRoute
  '/panel/echoes': typeof ProtectedPaneladminEchoesIndexRoute
  '/panel/materials': typeof ProtectedPaneladminMaterialsIndexRoute
  '/panel/resonators': typeof ProtectedPaneladminResonatorsIndexRoute
  '/panel/weapons': typeof ProtectedPaneladminWeaponsIndexRoute
  '/panel/roster': typeof ProtectedPanelguestRosterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/content/search': typeof ApiContentSearchRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_protected/panel/': typeof ProtectedPanelIndexRoute
  '/auth/error/': typeof AuthErrorIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/_protected/panel/(admin)/echoes/$id': typeof ProtectedPaneladminEchoesIdRoute
  '/_protected/panel/(admin)/echoes/create': typeof ProtectedPaneladminEchoesCreateRoute
  '/_protected/panel/(admin)/materials/$id': typeof ProtectedPaneladminMaterialsIdRoute
  '/_protected/panel/(admin)/materials/create': typeof ProtectedPaneladminMaterialsCreateRoute
  '/_protected/panel/(admin)/resonators/$id': typeof ProtectedPaneladminResonatorsIdRoute
  '/_protected/panel/(admin)/resonators/create': typeof ProtectedPaneladminResonatorsCreateRoute
  '/_protected/panel/(admin)/weapons/$id': typeof ProtectedPaneladminWeaponsIdRoute
  '/_protected/panel/(admin)/weapons/create': typeof ProtectedPaneladminWeaponsCreateRoute
  '/_protected/panel/(admin)/echoes/': typeof ProtectedPaneladminEchoesIndexRoute
  '/_protected/panel/(admin)/materials/': typeof ProtectedPaneladminMaterialsIndexRoute
  '/_protected/panel/(admin)/resonators/': typeof ProtectedPaneladminResonatorsIndexRoute
  '/_protected/panel/(admin)/weapons/': typeof ProtectedPaneladminWeaponsIndexRoute
  '/_protected/panel/(guest)/roster/': typeof ProtectedPanelguestRosterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/api/content/search'
    | '/api/rpc/$'
    | '/panel/'
    | '/auth/error/'
    | '/auth/login/'
    | '/panel/echoes/$id'
    | '/panel/echoes/create'
    | '/panel/materials/$id'
    | '/panel/materials/create'
    | '/panel/resonators/$id'
    | '/panel/resonators/create'
    | '/panel/weapons/$id'
    | '/panel/weapons/create'
    | '/panel/echoes/'
    | '/panel/materials/'
    | '/panel/resonators/'
    | '/panel/weapons/'
    | '/panel/roster/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/api/content/search'
    | '/api/rpc/$'
    | '/panel'
    | '/auth/error'
    | '/auth/login'
    | '/panel/echoes/$id'
    | '/panel/echoes/create'
    | '/panel/materials/$id'
    | '/panel/materials/create'
    | '/panel/resonators/$id'
    | '/panel/resonators/create'
    | '/panel/weapons/$id'
    | '/panel/weapons/create'
    | '/panel/echoes'
    | '/panel/materials'
    | '/panel/resonators'
    | '/panel/weapons'
    | '/panel/roster'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/(home)/'
    | '/api/auth/$'
    | '/api/content/search'
    | '/api/rpc/$'
    | '/_protected/panel/'
    | '/auth/error/'
    | '/auth/login/'
    | '/_protected/panel/(admin)/echoes/$id'
    | '/_protected/panel/(admin)/echoes/create'
    | '/_protected/panel/(admin)/materials/$id'
    | '/_protected/panel/(admin)/materials/create'
    | '/_protected/panel/(admin)/resonators/$id'
    | '/_protected/panel/(admin)/resonators/create'
    | '/_protected/panel/(admin)/weapons/$id'
    | '/_protected/panel/(admin)/weapons/create'
    | '/_protected/panel/(admin)/echoes/'
    | '/_protected/panel/(admin)/materials/'
    | '/_protected/panel/(admin)/resonators/'
    | '/_protected/panel/(admin)/weapons/'
    | '/_protected/panel/(guest)/roster/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  homeIndexRoute: typeof homeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiContentSearchRoute: typeof ApiContentSearchRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/error/': {
      id: '/auth/error/'
      path: '/error'
      fullPath: '/auth/error/'
      preLoaderRoute: typeof AuthErrorIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/panel/': {
      id: '/_protected/panel/'
      path: '/panel'
      fullPath: '/panel/'
      preLoaderRoute: typeof ProtectedPanelIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/search': {
      id: '/api/content/search'
      path: '/api/content/search'
      fullPath: '/api/content/search'
      preLoaderRoute: typeof ApiContentSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/panel/(guest)/roster/': {
      id: '/_protected/panel/(guest)/roster/'
      path: '/panel/roster'
      fullPath: '/panel/roster/'
      preLoaderRoute: typeof ProtectedPanelguestRosterIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/weapons/': {
      id: '/_protected/panel/(admin)/weapons/'
      path: '/panel/weapons'
      fullPath: '/panel/weapons/'
      preLoaderRoute: typeof ProtectedPaneladminWeaponsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/resonators/': {
      id: '/_protected/panel/(admin)/resonators/'
      path: '/panel/resonators'
      fullPath: '/panel/resonators/'
      preLoaderRoute: typeof ProtectedPaneladminResonatorsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/materials/': {
      id: '/_protected/panel/(admin)/materials/'
      path: '/panel/materials'
      fullPath: '/panel/materials/'
      preLoaderRoute: typeof ProtectedPaneladminMaterialsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/echoes/': {
      id: '/_protected/panel/(admin)/echoes/'
      path: '/panel/echoes'
      fullPath: '/panel/echoes/'
      preLoaderRoute: typeof ProtectedPaneladminEchoesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/weapons/create': {
      id: '/_protected/panel/(admin)/weapons/create'
      path: '/panel/weapons/create'
      fullPath: '/panel/weapons/create'
      preLoaderRoute: typeof ProtectedPaneladminWeaponsCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/weapons/$id': {
      id: '/_protected/panel/(admin)/weapons/$id'
      path: '/panel/weapons/$id'
      fullPath: '/panel/weapons/$id'
      preLoaderRoute: typeof ProtectedPaneladminWeaponsIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/resonators/create': {
      id: '/_protected/panel/(admin)/resonators/create'
      path: '/panel/resonators/create'
      fullPath: '/panel/resonators/create'
      preLoaderRoute: typeof ProtectedPaneladminResonatorsCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/resonators/$id': {
      id: '/_protected/panel/(admin)/resonators/$id'
      path: '/panel/resonators/$id'
      fullPath: '/panel/resonators/$id'
      preLoaderRoute: typeof ProtectedPaneladminResonatorsIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/materials/create': {
      id: '/_protected/panel/(admin)/materials/create'
      path: '/panel/materials/create'
      fullPath: '/panel/materials/create'
      preLoaderRoute: typeof ProtectedPaneladminMaterialsCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/materials/$id': {
      id: '/_protected/panel/(admin)/materials/$id'
      path: '/panel/materials/$id'
      fullPath: '/panel/materials/$id'
      preLoaderRoute: typeof ProtectedPaneladminMaterialsIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/echoes/create': {
      id: '/_protected/panel/(admin)/echoes/create'
      path: '/panel/echoes/create'
      fullPath: '/panel/echoes/create'
      preLoaderRoute: typeof ProtectedPaneladminEchoesCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/panel/(admin)/echoes/$id': {
      id: '/_protected/panel/(admin)/echoes/$id'
      path: '/panel/echoes/$id'
      fullPath: '/panel/echoes/$id'
      preLoaderRoute: typeof ProtectedPaneladminEchoesIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedPanelIndexRoute: typeof ProtectedPanelIndexRoute
  ProtectedPaneladminEchoesIdRoute: typeof ProtectedPaneladminEchoesIdRoute
  ProtectedPaneladminEchoesCreateRoute: typeof ProtectedPaneladminEchoesCreateRoute
  ProtectedPaneladminMaterialsIdRoute: typeof ProtectedPaneladminMaterialsIdRoute
  ProtectedPaneladminMaterialsCreateRoute: typeof ProtectedPaneladminMaterialsCreateRoute
  ProtectedPaneladminResonatorsIdRoute: typeof ProtectedPaneladminResonatorsIdRoute
  ProtectedPaneladminResonatorsCreateRoute: typeof ProtectedPaneladminResonatorsCreateRoute
  ProtectedPaneladminWeaponsIdRoute: typeof ProtectedPaneladminWeaponsIdRoute
  ProtectedPaneladminWeaponsCreateRoute: typeof ProtectedPaneladminWeaponsCreateRoute
  ProtectedPaneladminEchoesIndexRoute: typeof ProtectedPaneladminEchoesIndexRoute
  ProtectedPaneladminMaterialsIndexRoute: typeof ProtectedPaneladminMaterialsIndexRoute
  ProtectedPaneladminResonatorsIndexRoute: typeof ProtectedPaneladminResonatorsIndexRoute
  ProtectedPaneladminWeaponsIndexRoute: typeof ProtectedPaneladminWeaponsIndexRoute
  ProtectedPanelguestRosterIndexRoute: typeof ProtectedPanelguestRosterIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedPanelIndexRoute: ProtectedPanelIndexRoute,
  ProtectedPaneladminEchoesIdRoute: ProtectedPaneladminEchoesIdRoute,
  ProtectedPaneladminEchoesCreateRoute: ProtectedPaneladminEchoesCreateRoute,
  ProtectedPaneladminMaterialsIdRoute: ProtectedPaneladminMaterialsIdRoute,
  ProtectedPaneladminMaterialsCreateRoute:
    ProtectedPaneladminMaterialsCreateRoute,
  ProtectedPaneladminResonatorsIdRoute: ProtectedPaneladminResonatorsIdRoute,
  ProtectedPaneladminResonatorsCreateRoute:
    ProtectedPaneladminResonatorsCreateRoute,
  ProtectedPaneladminWeaponsIdRoute: ProtectedPaneladminWeaponsIdRoute,
  ProtectedPaneladminWeaponsCreateRoute: ProtectedPaneladminWeaponsCreateRoute,
  ProtectedPaneladminEchoesIndexRoute: ProtectedPaneladminEchoesIndexRoute,
  ProtectedPaneladminMaterialsIndexRoute:
    ProtectedPaneladminMaterialsIndexRoute,
  ProtectedPaneladminResonatorsIndexRoute:
    ProtectedPaneladminResonatorsIndexRoute,
  ProtectedPaneladminWeaponsIndexRoute: ProtectedPaneladminWeaponsIndexRoute,
  ProtectedPanelguestRosterIndexRoute: ProtectedPanelguestRosterIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthErrorIndexRoute: typeof AuthErrorIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthErrorIndexRoute: AuthErrorIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  homeIndexRoute: homeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiContentSearchRoute: ApiContentSearchRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
